---
version: "3.9"
services:
  frontend:
    image: eu.gcr.io/akvo-lumen/terria-maps/frontend:latest
    command: ["./start.sh"]
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
    ports:
      - 80:3001
