---
apiVersion: v1
kind: Service
metadata:
  name: terria-maps
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    run: terria-maps
